name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Set up Git LFS
    #   run: |
    #     git lfs install
    #     git lfs pull

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: capstone-c242-ps453

    - name: Authenticate Docker with GCP
      run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev

    - name: Build and push Docker image to Artifact Registry
      run: |
        IMAGE_NAME=asia-southeast2-docker.pkg.dev/capstone-c242-ps453/ml-vanillatech-repo/ml-vanillatech
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: capstone-c242-ps453

    - name: Deploy to Cloud Run
      run: |
        IMAGE_NAME=asia-southeast2-docker.pkg.dev/capstone-c242-ps453/ml-vanillatech-repo/ml-vanillatech
        gcloud run deploy ml-vanillatech \
          --image $IMAGE_NAME \
          --region asia-southeast2 \
          --platform managed \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 2
