name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  installation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: capstone-c242-ps453

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: installation

    steps:
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: capstone-c242-ps453

    - name: Deploy to Google Cloud Functions
      run: |
        gcloud functions deploy listen_to_pubsub \
          --runtime python310 \
          --trigger-topic process-image-sub \
          --allow-unauthenticated \
          --region asia-southeast2 \
          --entry-point listen_to_pubsub \
          --source . \
          --memory 2048MB
